services:
  sqlite:
    container_name: sqlite-container
    image: nouchka/sqlite3:latest
    volumes:
      - sqlite-data:/db

  bot:
    container_name: homework-bot-container
    build: .
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - sqlite
    restart: always

volumes:
  sqlite-data:
